import { Injectable } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { Observable } from 'rxjs';

@Injectable({
  providedIn: 'root'
})
export class StripeServiceService {
  private apiUrl = 'https://www.ttoffer.com'; // Update with your actual backend API endpoint

  constructor(private http: HttpClient) {}

  /**
   * Processes a payment with the token created by Stripe and the specified amount.
   * @param token - The payment token generated by Stripe.
   * @param amount - The amount to be charged (in dollars).
   * @returns An Observable containing the response from the backend.
   */
  processPayment(token: any, amount: number): Observable<any> {
    return this.http.post(`${this.apiUrl}/payment`, {
      token: token.id,
      amount: amount * 100 // Convert amount to cents (Stripe expects the smallest currency unit)
    });
  }

  /**
   * Initializes and returns a Stripe instance using the public key.
   * @returns Stripe instance for processing payments.
   */
  getStripe() {
    return window.Stripe ? window.Stripe('pk_test_51PZehdRp8Vcq4D6bi1HEniPgkPluHHZftNgeONrtcYRrsR0bs4GN6xSEnrBzE76rze7bTA63a3KecIwnO28ebJnJ00lTSTShq9') : null;
  }
}
